// ============================================
// ArmrData — lang.js — Vèsyon Konplè
// Kreyòl | Français | English
// ============================================

// ── TRADIKSYON PRENSIPAL ──
const translations = {

  index: {
    ht: {
      nav_brand:"ArmrData", nav_akèy:"Akèy", nav_apropos:"À Propos",
      nav_sevis:"Sèvis", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Afilyasyon", nav_kontak:"Kontak",
      hero_eyebrow:"// ArmrData Cybersecurity",
      hero_line1:"Pwoteje Done Ou.", hero_line2:"Pwoteje Biznis Ou.",
      hero_line3:"Pwoteje Avni Dijital Ou.",
      hero_desc:"Nou ede moun, antrepriz ak òganizasyon pwoteje done yo kont menas dijital yo — ak ekspètiz, teknoloji ak angajman.",
      btn_sevis:"Dekouvri Sèvis Nou →", btn_kontak:"Kontakte Nou",
      stat1_num:"100%", stat1_label:"Konfidansyalite Garanti",
      stat2_num:"<24h", stat2_label:"Tan Repons",
      stat3_num:"3", stat3_label:"Lang Disponib",
      qs_title:"// Sèvis Prensipal",
      qs1_name:"Sibèsekirite", qs1_desc:"Pwoteksyon rezo, sistèm ak done",
      qs2_name:"Tès Penetrasyon", qs2_desc:"Detekte feblès avan atakè yo",
      qs3_name:"Fòmasyon", qs3_desc:"Ekip ou pwoteje, biznis ou solid",
      qs4_name:"Odit Sekirite", qs4_desc:"Evalyasyon konplè sistèm ou",
      cta_title:"📖 Blendaj Dijital",
      cta_desc:"7 etap pou pwoteje tèt ou ak biznis ou kont pirat — disponib an Kreyòl, Français ak English.",
      cta_btn:"Dekouvri Ebook la", footer_tag:"Securing your dataworld!"
    },
    fr: {
      nav_brand:"ArmrData", nav_akèy:"Accueil", nav_apropos:"À Propos",
      nav_sevis:"Services", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Affiliation", nav_kontak:"Contact",
      hero_eyebrow:"// ArmrData Cybersécurité",
      hero_line1:"Protégez Vos Données.", hero_line2:"Protégez Votre Entreprise.",
      hero_line3:"Protégez Votre Avenir Numérique.",
      hero_desc:"Nous aidons les particuliers, les entreprises et les organisations à protéger leurs données contre les menaces numériques.",
      btn_sevis:"Découvrir Nos Services →", btn_kontak:"Nous Contacter",
      stat1_num:"100%", stat1_label:"Confidentialité Garantie",
      stat2_num:"<24h", stat2_label:"Temps de Réponse",
      stat3_num:"3", stat3_label:"Langues Disponibles",
      qs_title:"// Services Principaux",
      qs1_name:"Cybersécurité", qs1_desc:"Protection réseau, systèmes et données",
      qs2_name:"Test de Pénétration", qs2_desc:"Détectez les failles avant les attaquants",
      qs3_name:"Formation", qs3_desc:"Équipe protégée, entreprise solide",
      qs4_name:"Audit de Sécurité", qs4_desc:"Évaluation complète de votre système",
      cta_title:"📖 Blindage Digital",
      cta_desc:"7 étapes pour vous protéger contre les pirates — disponible en Créole, Français et Anglais.",
      cta_btn:"Découvrir l'Ebook", footer_tag:"Securing your dataworld!"
    },
    en: {
      nav_brand:"ArmrData", nav_akèy:"Home", nav_apropos:"About",
      nav_sevis:"Services", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Affiliate", nav_kontak:"Contact",
      hero_eyebrow:"// ArmrData Cybersecurity",
      hero_line1:"Protect Your Data.", hero_line2:"Protect Your Business.",
      hero_line3:"Protect Your Digital Future.",
      hero_desc:"We help individuals, businesses and organizations protect their data against digital threats — with expertise, technology and commitment.",
      btn_sevis:"Discover Our Services →", btn_kontak:"Contact Us",
      stat1_num:"100%", stat1_label:"Guaranteed Confidentiality",
      stat2_num:"<24h", stat2_label:"Response Time",
      stat3_num:"3", stat3_label:"Available Languages",
      qs_title:"// Main Services",
      qs1_name:"Cybersecurity", qs1_desc:"Network, system and data protection",
      qs2_name:"Penetration Testing", qs2_desc:"Detect vulnerabilities before attackers",
      qs3_name:"Training", qs3_desc:"Protected team, solid business",
      qs4_name:"Security Audit", qs4_desc:"Complete evaluation of your system",
      cta_title:"📖 Digital Shield",
      cta_desc:"7 steps to protect yourself and your business against hackers — available in Creole, French and English.",
      cta_btn:"Discover the Ebook", footer_tag:"Securing your dataworld!"
    }
  },

  apropos: {
    ht: {
      nav_brand:"ArmrData", nav_akèy:"Akèy", nav_apropos:"À Propos",
      nav_sevis:"Sèvis", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Afilyasyon", nav_kontak:"Kontak",
      hero_eyebrow:"À Propos",
      hero_title1:"Pwoteje done ou —", hero_title2:"se misyon nou.",
      hero_desc:"ArmrData se yon inisyativ ki fèt pou ede moun ak antrepriz yo pwoteje done yo, amelyore sekirite dijital yo epi devlope bon pratik cybersécurité nan yon mond kote menas dijital yo ap ogmante chak jou.",
      misyon_label:"Misyon Nou", misyon_title:"Sekirite pou tout moun",
      misyon_desc:"Ede moun ak biznis yo pwoteje enfòmasyon yo kont menas dijital modèn yo — aksesib, senp, efikas.",
      vizyon_label:"Vizyon Nou", vizyon_title:"Referans Karayib la",
      vizyon_desc:"Vin yon referans nan domèn cybersécurité nan Karayib la ak pi lwen toujou.",
      vale_title:"Valè Nou Yo",
      vale1:"Konfyans", vale2:"Profesyonalis", vale3:"Inovasyon",
      vale4:"Entegrite", vale5:"Pwoteksyon",
      footer_tag:"Securing your dataworld!"
    },
    fr: {
      nav_brand:"ArmrData", nav_akèy:"Accueil", nav_apropos:"À Propos",
      nav_sevis:"Services", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Affiliation", nav_kontak:"Contact",
      hero_eyebrow:"À Propos",
      hero_title1:"Protégez vos données —", hero_title2:"c'est notre mission.",
      hero_desc:"ArmrData est une initiative créée pour aider les particuliers et les entreprises à protéger leurs données, améliorer leur sécurité numérique et développer de bonnes pratiques de cybersécurité.",
      misyon_label:"Notre Mission", misyon_title:"La sécurité pour tous",
      misyon_desc:"Aider les particuliers et les entreprises à protéger leurs informations contre les menaces numériques modernes — accessible, simple, efficace.",
      vizyon_label:"Notre Vision", vizyon_title:"Référence des Caraïbes",
      vizyon_desc:"Devenir une référence en cybersécurité dans les Caraïbes et au-delà.",
      vale_title:"Nos Valeurs",
      vale1:"Confiance", vale2:"Professionnalisme", vale3:"Innovation",
      vale4:"Intégrité", vale5:"Protection",
      footer_tag:"Securing your dataworld!"
    },
    en: {
      nav_brand:"ArmrData", nav_akèy:"Home", nav_apropos:"About",
      nav_sevis:"Services", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Affiliate", nav_kontak:"Contact",
      hero_eyebrow:"About",
      hero_title1:"Protect your data —", hero_title2:"that's our mission.",
      hero_desc:"ArmrData is an initiative created to help individuals and businesses protect their data, improve their digital security and develop good cybersecurity practices.",
      misyon_label:"Our Mission", misyon_title:"Security for everyone",
      misyon_desc:"Help individuals and businesses protect their information against modern digital threats — accessible, simple, effective.",
      vizyon_label:"Our Vision", vizyon_title:"Caribbean Reference",
      vizyon_desc:"Become a reference in cybersecurity in the Caribbean and beyond.",
      vale_title:"Our Values",
      vale1:"Trust", vale2:"Professionalism", vale3:"Innovation",
      vale4:"Integrity", vale5:"Protection",
      footer_tag:"Securing your dataworld!"
    }
  },

  blog: {
    ht: {
      nav_brand:"ArmrData", nav_akèy:"Akèy", nav_apropos:"À Propos",
      nav_sevis:"Sèvis", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Afilyasyon", nav_kontak:"Kontak",
      hero_eyebrow:"// Blog", hero_title1:"Sant Konesans", hero_title2:"ArmrData",
      hero_desc:"Byenveni nan Sant Konesans ArmrData. Objektif nou se ede moun ak antrepriz yo konprann pi byen menas dijital yo epi devlope bon abitid sekirite.",
      tag_tout:"Tout", tag_modpas:"Modpas", tag_phishing:"Phishing",
      tag_facebook:"Facebook", tag_rezo:"Rezo",
      art1_tag:"Rezo Sosyal", art1_date:"Jen 2026",
      art1_title:"5 Erè Sekirite Moun Fè Sou Facebook",
      art1_desc:"Dekouvri erè ki pi komen itilizatè Facebook yo fè epi kijan pou evite yo.",
      art2_tag:"Modpas", art2_date:"Jen 2026",
      art2_title:"Kijan Pou Kreye Yon Modpas Fò An 2026",
      art2_desc:"Konprann enpòtans yon modpas fò ak risk ki genyen lè yon modpas fèb.",
      art3_tag:"Phishing", art3_date:"Jen 2026",
      art3_title:"Phishing: Pi Gwo Pyèj Dijital Jodi a",
      art3_desc:"Aprann kijan atakan yo itilize phishing pou twonpe viktim yo ak kijan pou pwoteje tèt ou.",
      read_btn:"Li Atik la →",
      cta_title:"Ale Pi Lwen Ak Blendaj Dijital",
      cta_desc:"Atik gratis yo se sèlman yon entwodiksyon. Pou aprann teknik pwofesyonèl yo itilize pou pwoteje tèt yo ak biznis yo, dekouvri ebook nou an.",
      cta_btn:"Dekouvri Ebook la", footer_tag:"Securing your dataworld!"
    },
    fr: {
      nav_brand:"ArmrData", nav_akèy:"Accueil", nav_apropos:"À Propos",
      nav_sevis:"Services", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Affiliation", nav_kontak:"Contact",
      hero_eyebrow:"// Blog", hero_title1:"Centre de Connaissances", hero_title2:"ArmrData",
      hero_desc:"Bienvenue au Centre de Connaissances ArmrData. Notre objectif est d'aider les particuliers et les entreprises à mieux comprendre les menaces numériques et à développer de bonnes habitudes de sécurité.",
      tag_tout:"Tout", tag_modpas:"Mot de passe", tag_phishing:"Phishing",
      tag_facebook:"Facebook", tag_rezo:"Réseau",
      art1_tag:"Réseau Social", art1_date:"Juin 2026",
      art1_title:"5 Erreurs de Sécurité que les Gens Font sur Facebook",
      art1_desc:"Découvrez les erreurs les plus courantes des utilisateurs Facebook et comment les éviter.",
      art2_tag:"Mot de passe", art2_date:"Juin 2026",
      art2_title:"Comment Créer un Mot de Passe Fort en 2026",
      art2_desc:"Comprendre l'importance d'un mot de passe fort et les risques d'un mot de passe faible.",
      art3_tag:"Phishing", art3_date:"Juin 2026",
      art3_title:"Phishing: Le Plus Grand Piège Numérique Aujourd'hui",
      art3_desc:"Apprenez comment les attaquants utilisent le phishing pour tromper leurs victimes.",
      read_btn:"Lire l'Article →",
      cta_title:"Allez Plus Loin Avec Blindage Digital",
      cta_desc:"Les articles gratuits ne sont qu'une introduction. Pour apprendre les techniques professionnelles, découvrez notre ebook.",
      cta_btn:"Découvrir l'Ebook", footer_tag:"Securing your dataworld!"
    },
    en: {
      nav_brand:"ArmrData", nav_akèy:"Home", nav_apropos:"About",
      nav_sevis:"Services", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Affiliate", nav_kontak:"Contact",
      hero_eyebrow:"// Blog", hero_title1:"Knowledge Center", hero_title2:"ArmrData",
      hero_desc:"Welcome to the ArmrData Knowledge Center. Our goal is to help individuals and businesses better understand digital threats and develop good security habits.",
      tag_tout:"All", tag_modpas:"Password", tag_phishing:"Phishing",
      tag_facebook:"Facebook", tag_rezo:"Network",
      art1_tag:"Social Media", art1_date:"June 2026",
      art1_title:"5 Security Mistakes People Make on Facebook",
      art1_desc:"Discover the most common mistakes Facebook users make and how to avoid them.",
      art2_tag:"Password", art2_date:"June 2026",
      art2_title:"How to Create a Strong Password in 2026",
      art2_desc:"Understand the importance of a strong password and the risks of a weak one.",
      art3_tag:"Phishing", art3_date:"June 2026",
      art3_title:"Phishing: The Biggest Digital Trap Today",
      art3_desc:"Learn how attackers use phishing to trick their victims and how to protect yourself.",
      read_btn:"Read Article →",
      cta_title:"Go Further With Digital Shield",
      cta_desc:"Free articles are just an introduction. To learn professional techniques, discover our ebook.",
      cta_btn:"Discover the Ebook", footer_tag:"Securing your dataworld!"
    }
  },

  ebook: {
    ht: {
      nav_brand:"ArmrData", nav_akèy:"Akèy", nav_apropos:"À Propos",
      nav_sevis:"Sèvis", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Afilyasyon", nav_kontak:"Kontak",
      hero_eyebrow:"// E-Book", hero_title:"E-Book ArmrData",
      hero_sub:"Pwoteksyon dijital nan men ou", badge:"⭐ Liv Vedèt",
      book_title:"📋 Blendaj Dijital",
      book_desc:"7 etap pou pwoteje tèt ou ak biznis ou kont pirat.",
      feat1:"Kreyòl Ayisyen", feat2:"Français", feat3:"English",
      feat4:"Pou moun ak antrepriz",
      price_label:"Pri", price_main:"$14.99 USD", price_alt:"oswa 1 500 HTG",
      lang_title:"🌐 Chwazi Lang Ou",
      lang1_name:"Kreyòl Ayisyen", lang1_sub:"Vèsyon orijinal la.",
      lang2_name:"Français", lang2_sub:"Version française.",
      lang3_name:"English", lang3_sub:"English edition.",
      buy_title:"📱 Kijan Pou Achte Liv la?",
      step1:"Klike sou \"Achte Kounye a\"", step2:"Fè peman MonCash",
      step3:"Voye resi peman an", step4:"Resevwa liv la pa imèl",
      step_note:"🔒 Apre konfimasyon peman an, ou ap resevwa vèsyon lang ou te chwazi a.",
      btn_preview:"Li Apèsi →", btn_buy:"Achte Kounye a",
      footer_tag:"Securing your dataworld!"
    },
    fr: {
      nav_brand:"ArmrData", nav_akèy:"Accueil", nav_apropos:"À Propos",
      nav_sevis:"Services", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Affiliation", nav_kontak:"Contact",
      hero_eyebrow:"// E-Book", hero_title:"E-Book ArmrData",
      hero_sub:"La protection numérique entre vos mains", badge:"⭐ Livre Vedette",
      book_title:"📋 Blindage Digital",
      book_desc:"7 étapes pour protéger vous et votre entreprise contre les pirates.",
      feat1:"Créole Haïtien", feat2:"Français", feat3:"English",
      feat4:"Pour particuliers et entreprises",
      price_label:"Prix", price_main:"$14.99 USD", price_alt:"ou 1 500 HTG",
      lang_title:"🌐 Choisissez Votre Langue",
      lang1_name:"Kreyòl Ayisyen", lang1_sub:"Version originale.",
      lang2_name:"Français", lang2_sub:"Version française.",
      lang3_name:"English", lang3_sub:"English edition.",
      buy_title:"📱 Comment Acheter le Livre?",
      step1:"Cliquez sur \"Acheter Maintenant\"",
      step2:"Effectuez le paiement MonCash",
      step3:"Envoyez le reçu de paiement",
      step4:"Recevez le livre par email",
      step_note:"🔒 Après confirmation du paiement, vous recevrez la version dans la langue choisie.",
      btn_preview:"Lire l'Aperçu →", btn_buy:"Acheter Maintenant",
      footer_tag:"Securing your dataworld!"
    },
    en: {
      nav_brand:"ArmrData", nav_akèy:"Home", nav_apropos:"About",
      nav_sevis:"Services", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Affiliate", nav_kontak:"Contact",
      hero_eyebrow:"// E-Book", hero_title:"ArmrData E-Book",
      hero_sub:"Digital protection in your hands", badge:"⭐ Featured Book",
      book_title:"📋 Digital Shield",
      book_desc:"7 steps to protect yourself and your business against hackers.",
      feat1:"Haitian Creole", feat2:"Français", feat3:"English",
      feat4:"For individuals and businesses",
      price_label:"Price", price_main:"$14.99 USD", price_alt:"or 1,500 HTG",
      lang_title:"🌐 Choose Your Language",
      lang1_name:"Kreyòl Ayisyen", lang1_sub:"Original version.",
      lang2_name:"Français", lang2_sub:"French version.",
      lang3_name:"English", lang3_sub:"English edition.",
      buy_title:"📱 How to Buy the Book?",
      step1:"Click \"Buy Now\"", step2:"Make MonCash payment",
      step3:"Send payment receipt", step4:"Receive the book by email",
      step_note:"🔒 After payment confirmation, you will receive the version in your chosen language.",
      btn_preview:"Read Preview →", btn_buy:"Buy Now",
      footer_tag:"Securing your dataworld!"
    }
  },

  afilyasyon: {
    ht: {
      nav_brand:"ArmrData", nav_akèy:"Akèy", nav_apropos:"À Propos",
      nav_sevis:"Sèvis", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Afilyasyon", nav_kontak:"Kontak",
      hero_eyebrow:"// Afilyasyon",
      hero_title1:"Vin Patnè", hero_title2:"ArmrData",
      hero_desc:"Antrepriz ou a ka vin yon patnè ArmrData pou jwenn sèvis cybersécurité pi fasil, resevwa sipò espesyalize epi devlope yon relasyon pwofesyonèl ki dire lontan.",
      why_label:"// Poukisa", why_title:"Poukisa Vin Patnè ArmrData?",
      av1_title:"Sipò Pwofesyonèl", av1_desc:"Aksè ak ekspètiz ekip ArmrData a pou ede w pran pi bon desizyon yo.",
      av2_title:"Priyorite", av2_desc:"Patnè yo jwenn tretman priyoritè sou demann ak kestyon yo.",
      av3_title:"Kolaborasyon", av3_desc:"Travay ansanm sou pwojè, fòmasyon ak inisyativ sekirite dijital.",
      av4_title:"Komisyon", av4_desc:"Jwenn komisyon sou kliyan ak pwojè ou refere bay ArmrData.",
      konfid_title:"Konfidansyalite Garanti",
      konfid_desc:"Tout enfòmasyon antrepriz ou soumèt yo pwoteje epi trete avèk konfidansyalite.",
      form_label:"// Fòm Afilyasyon",
      ph_non:"Non", ph_siyati:"Siyati", ph_imel:"Imèl",
      ph_antrepriz:"Non Antrepriz", ph_adrès:"Adrès Antrepriz",
      ph_imel_ant:"Imèl Antrepriz", ph_tel:"Telefòn",
      ph_sit:"Sit entènèt (opsyonèl)", btn_submit:"Afilye Kounye a",
      footer_tag:"Securing your dataworld!"
    },
    fr: {
      nav_brand:"ArmrData", nav_akèy:"Accueil", nav_apropos:"À Propos",
      nav_sevis:"Services", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Affiliation", nav_kontak:"Contact",
      hero_eyebrow:"// Affiliation",
      hero_title1:"Devenez Partenaire", hero_title2:"ArmrData",
      hero_desc:"Votre entreprise peut devenir un partenaire ArmrData pour accéder plus facilement aux services de cybersécurité, recevoir un support spécialisé et développer une relation professionnelle durable.",
      why_label:"// Pourquoi", why_title:"Pourquoi Devenir Partenaire ArmrData?",
      av1_title:"Support Professionnel", av1_desc:"Accès à l'expertise de l'équipe ArmrData pour prendre les meilleures décisions.",
      av2_title:"Priorité", av2_desc:"Les partenaires bénéficient d'un traitement prioritaire sur les demandes et questions.",
      av3_title:"Collaboration", av3_desc:"Travailler ensemble sur des projets, formations et initiatives de sécurité numérique.",
      av4_title:"Commission", av4_desc:"Gagnez des commissions sur les clients et projets que vous référez à ArmrData.",
      konfid_title:"Confidentialité Garantie",
      konfid_desc:"Toutes les informations de votre entreprise sont protégées et traitées avec confidentialité.",
      form_label:"// Formulaire d'Affiliation",
      ph_non:"Prénom", ph_siyati:"Nom de famille", ph_imel:"Email",
      ph_antrepriz:"Nom de l'entreprise", ph_adrès:"Adresse de l'entreprise",
      ph_imel_ant:"Email professionnel", ph_tel:"Téléphone",
      ph_sit:"Site web (optionnel)", btn_submit:"S'affilier Maintenant",
      footer_tag:"Securing your dataworld!"
    },
    en: {
      nav_brand:"ArmrData", nav_akèy:"Home", nav_apropos:"About",
      nav_sevis:"Services", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Affiliate", nav_kontak:"Contact",
      hero_eyebrow:"// Affiliate",
      hero_title1:"Become a Partner", hero_title2:"ArmrData",
      hero_desc:"Your company can become an ArmrData partner to access cybersecurity services more easily, receive specialized support and develop a lasting professional relationship.",
      why_label:"// Why", why_title:"Why Become an ArmrData Partner?",
      av1_title:"Professional Support", av1_desc:"Access to ArmrData team expertise to help you make the best decisions.",
      av2_title:"Priority", av2_desc:"Partners receive priority treatment on requests and questions.",
      av3_title:"Collaboration", av3_desc:"Work together on projects, training and digital security initiatives.",
      av4_title:"Commission", av4_desc:"Earn commissions on clients and projects you refer to ArmrData.",
      konfid_title:"Guaranteed Confidentiality",
      konfid_desc:"All information your company submits is protected and treated with confidentiality.",
      form_label:"// Affiliate Form",
      ph_non:"First name", ph_siyati:"Last name", ph_imel:"Email",
      ph_antrepriz:"Company name", ph_adrès:"Company address",
      ph_imel_ant:"Professional email", ph_tel:"Phone",
      ph_sit:"Website (optional)", btn_submit:"Affiliate Now",
      footer_tag:"Securing your dataworld!"
    }
  },

  kontak: {
    ht: {
      nav_brand:"ArmrData", nav_akèy:"Akèy", nav_apropos:"À Propos",
      nav_sevis:"Sèvis", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Afilyasyon", nav_kontak:"Kontak",
      hero_eyebrow:"// Kontak", hero_title1:"Kontakte", hero_title2:"ArmrData",
      hero_desc:"Yon kesyon, yon pwojè, oswa yon ijans? Ekip nou an la pou reponn ou rapidman ak pwofesyonalis.",
      ijans_label:"⚠ Ijans Sekirite",
      ijans_title:"🚨 Èske w anba yon atak enfòmatik kounye a?",
      ijans_desc:"Pa pèdi tan. Rele nou dirèkteman sou nimewo ijans nou an — ekip nou an disponib pou reponn rapid.",
      ijans_btn:"🔴 Rele Ijans — +509 37 88 6919",
      form_label:"// Voye yon Mesaj",
      ph_non:"Non Konplè / Non Konpayi", ph_imel:"Imèl Pwofesyonèl",
      ph_sijè:"Sijè — Chwazi youn",
      opt1:"Mande yon Odit", opt2:"Kesyon sou Fòmasyon",
      opt3:"Afilyasyon", opt4:"Sipò Teknik", opt5:"Lòt",
      ph_mesaj:"Mesaj ou — eksplike bezwen ou an ak detay",
      btn_send:"Voye Mesaj →", info_label:"// Enfòmasyon Dirèk",
      imel_label:"Imèl", wa_label:"WhatsApp / Telefòn",
      repons_label:"⏱ Tan Repons", repons_title:"✅ Repons Garanti",
      repons_desc:"N ap reponn ou nan mwens pase 24 èdtan — paske nou respekte tan ou epi nou òganize pou ba ou pi bon sèvis la.",
      repons_badge:"⚡ Mwens pase 24h", footer_tag:"Securing your dataworld!"
    },
    fr: {
      nav_brand:"ArmrData", nav_akèy:"Accueil", nav_apropos:"À Propos",
      nav_sevis:"Services", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Affiliation", nav_kontak:"Contact",
      hero_eyebrow:"// Contact", hero_title1:"Contactez", hero_title2:"ArmrData",
      hero_desc:"Une question, un projet ou une urgence? Notre équipe est là pour vous répondre rapidement et professionnellement.",
      ijans_label:"⚠ Urgence Sécurité",
      ijans_title:"🚨 Êtes-vous sous une cyberattaque en ce moment?",
      ijans_desc:"Ne perdez pas de temps. Appelez-nous directement sur notre numéro d'urgence.",
      ijans_btn:"🔴 Appel Urgence — +509 37 88 6919",
      form_label:"// Envoyer un Message",
      ph_non:"Nom Complet / Nom de Société", ph_imel:"Email Professionnel",
      ph_sijè:"Sujet — Choisissez un",
      opt1:"Demander un Audit", opt2:"Questions sur la Formation",
      opt3:"Affiliation", opt4:"Support Technique", opt5:"Autre",
      ph_mesaj:"Votre message — expliquez votre besoin en détail",
      btn_send:"Envoyer le Message →", info_label:"// Informations Directes",
      imel_label:"Email", wa_label:"WhatsApp / Téléphone",
      repons_label:"⏱ Temps de Réponse", repons_title:"✅ Réponse Garantie",
      repons_desc:"Nous vous répondrons en moins de 24 heures — parce que nous respectons votre temps.",
      repons_badge:"⚡ Moins de 24h", footer_tag:"Securing your dataworld!"
    },
    en: {
      nav_brand:"ArmrData", nav_akèy:"Home", nav_apropos:"About",
      nav_sevis:"Services", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Affiliate", nav_kontak:"Contact",
      hero_eyebrow:"// Contact", hero_title1:"Contact", hero_title2:"ArmrData",
      hero_desc:"A question, a project, or an emergency? Our team is here to respond quickly and professionally.",
      ijans_label:"⚠ Security Emergency",
      ijans_title:"🚨 Are you under a cyberattack right now?",
      ijans_desc:"Don't waste time. Call us directly on our emergency number.",
      ijans_btn:"🔴 Emergency Call — +509 37 88 6919",
      form_label:"// Send a Message",
      ph_non:"Full Name / Company Name", ph_imel:"Professional Email",
      ph_sijè:"Subject — Choose one",
      opt1:"Request an Audit", opt2:"Training Questions",
      opt3:"Affiliate", opt4:"Technical Support", opt5:"Other",
      ph_mesaj:"Your message — explain your needs in detail",
      btn_send:"Send Message →", info_label:"// Direct Information",
      imel_label:"Email", wa_label:"WhatsApp / Phone",
      repons_label:"⏱ Response Time", repons_title:"✅ Guaranteed Response",
      repons_desc:"We will respond to you in less than 24 hours — because we respect your time.",
      repons_badge:"⚡ Less than 24h", footer_tag:"Securing your dataworld!"
    }
  },

  sevis: {
    ht: {
      nav_brand:"ArmrData", nav_akèy:"Akèy", nav_apropos:"À Propos",
      nav_sevis:"Sèvis", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Afilyasyon", nav_kontak:"Kontak",
      hero_eyebrow:"// Sèvis", hero_title:"Sèvis ArmrData",
      hero_desc:"Nou ede moun, antrepriz ak òganizasyon pwoteje done yo kont menas dijital yo.",
      antrepriz_label:"// Pou Antrepriz", moun_label:"// Pou Moun",
      btn_learn:"Aprann Plis →",
      price_label:"Pri Sèvis", price_val:"A pati de $39.99 USD oswa 5 000 Goud",
      ph_antrepriz:"Non Antrepriz", ph_adrès:"Adrès Antrepriz",
      ph_imel:"Imèl Antrepriz", ph_kòmantè:"Kòmantè — detaye sèvis ou bezwen an",
      btn_confirm:"Mwen Dakò ✓", footer_tag:"Securing your dataworld!",
      s1_title:"Sibèsekirite", s1_desc:"Pwoteksyon rezo, sistèm ak done sansib.",
      s1_modal_desc:"Pwoteksyon rezo, sistèm ak done sansib pou antrepriz ou a kont tout menas dijital modèn yo.",
      s2_title:"Tès Penetrasyon", s2_desc:"Detekte feblès sekirite yo avan atakè yo.",
      s2_modal_desc:"Detekte feblès sekirite yo avan atakè yo — yon ekip espesyalize teste sistèm ou pou jwenn pòt ki louvri yo.",
      s3_title:"Sekirite Cloud", s3_desc:"Pwoteje enfrastrikti cloud ak sèvis dijital yo.",
      s3_modal_desc:"Pwoteje enfrastrikti cloud ak sèvis dijital yo kont atak ak aksè non otorize.",
      s4_title:"Analiz Dijital", s4_desc:"Ankèt sou ensidan enfòmatik ak rekiperasyon prèv.",
      s4_modal_desc:"Ankèt sou ensidan enfòmatik ak rekiperasyon prèv — idantifye sous atak la epi dokimante prèv yo.",
      s5_title:"Fòmasyon", s5_desc:"Fòmasyon espesyalize pou ekip ak antrepriz sou sekirite dijital.",
      s5_modal_desc:"Fòmasyon espesyalize pou ekip ak antrepriz sou sekirite dijital — aprann pwoteje sistèm ou yo efikasman.",
      s6_title:"Odit Sekirite", s6_desc:"Evalyasyon konplè sistèm sekirite antrepriz ou pou idantifye risk yo.",
      s6_modal_desc:"Evalyasyon konplè sistèm sekirite antrepriz ou pou idantifye risk yo ak rekòmande solisyon.",
      s7_title:"Pwoteksyon Done Pèsonèl", s7_desc:"Pwoteje enfòmasyon pèsonèl ou kont vòl ak fwod.",
      s7_modal_desc:"Pwoteje enfòmasyon pèsonèl ou kont vòl ak fwod — sekirize idantite dijital ou.",
      s8_title:"Sekirite Aparèy", s8_desc:"Pwoteksyon telefòn, tablèt ak òdinatè.",
      s8_modal_desc:"Pwoteksyon telefòn, tablèt ak òdinatè kont menas ak aksè ilegal.",
      s9_title:"Sibèsekirite Pèsonèl", s9_desc:"Pwoteksyon rezo, sistèm ak done pèsonèl ou yo.",
      s9_modal_desc:"Pwoteksyon rezo, sistèm ak done pèsonèl ou yo kont tout menas dijital.",
      s10_title:"Tès Penetrasyon Pèsonèl", s10_desc:"Detekte feblès sekirite nan sistèm pèsonèl ou avan atakè yo.",
      s10_modal_desc:"Detekte feblès sekirite nan sistèm pèsonèl ou avan atakè yo jwenn yo.",
      // PRI ENDIVIDYÈL
      p7_pri:"À pati de $44.99 USD oswa 5 880 Goud",
      p8_pri:"À pati de $35 USD oswa 4 500 Goud",
      p9_pri:"À pati de $50 USD oswa 6 500 Goud",
      p10_pri:"À pati de $99.99 USD oswa 13 000 Goud",
      // PRI PME
      p1_pri:"À pati de $110 USD oswa 14 380 Goud",
      p2_pri:"À pati de $190 USD oswa 24 800 Goud",
      p3_pri:"À pati de $165 USD oswa 21 500 Goud",
      p4_pri_title:"Ankèt apre ensidan enfòmatik",
      p4_pri_base:"Analiz debaz: $175 USD oswa 22 800 Goud",
      p4_pri_full:"Ankèt konplè: $310 USD+ oswa 40 500+ Goud",
      p4_pri_special:"Ka espesyal: Sou devis",
      p5_pri_title:"Pri sèvis:",
      p5_pri_group:"Gwoup 10-20 moun: $250 USD oswa 32 600 Goud",
      p5_pri_biz:"Antrepriz: $500 USD oswa 65 360 Goud",
      p6_pri_web:"Odit Sit Web: $110 USD oswa 14 380 Goud",
      p6_pri_biz:"Odit Biznis: $300 USD oswa 39 200 Goud",
      p6_pri_pme:"Odit Antrepriz (PME): $650 USD+ oswa 84 960 Goud",
      // KONSILTASYON
      konsilt_ind_title:"Pri Konsiltasyon:",
      konsilt_ind_30:"30 minit: $12.99 USD oswa 1 700 Goud",
      konsilt_ind_60:"1 èdtan: $25 USD oswa 3 250 Goud",
      konsilt_pme_30:"30 minit: $15 USD oswa 1 960 Goud",
      konsilt_pme_60:"1 èdtan: $30 USD oswa 3 900 Goud",
      konsilt_pme_plan:"Plan estratejik: $90 USD+ oswa 11 760+ Goud",
      konsilt_ong:"Sou demann — Devis pèsonalize",
      ong_pri:"Sou demann (Devis pèsonalize). Kontakte nou pou yon analiz bezwen espesifik.",
      cta_rele:"📞 Rele Nou pou yon Evalyasyon Gratis",
      pake_label:"// Chwazi Pake Ou",
      pake1_title:"👤 Pake Endividyèl (Sekirite Pèsonalite)",
      pake1_desc:"Ideyal pou moun ki vle pwoteje enfòmasyon prive yo, kont sosyal yo, ak telefòn yo.",
      pake2_title:"🏢 Pake PME (Ti ak Mwayen Antrepriz)",
      pake2_desc:"Ideyal pou biznis ki vle sekirize rezo yo ak enfòmasyon kliyan yo.",
      pake3_title:"🏛️ Pake ONG & Gwo Antrepriz (Enterprise)",
      pake3_desc:"Solisyon avanse pou òganizasyon ki gen gwo volim done ak bezwen konfòmite.",
      konsilt_title:"Konsiltasyon Dijital",
      konsilt_desc:"Pale ak yon ekspè ArmrData gratis",
      meto_label:"// Metodoloji Nou An",
      meto1_name:"🔍 Analiz", meto1_desc:"Nou evalye nivo risk aktyèl ou.",
      meto2_name:"🎯 Deteksyon", meto2_desc:"Nou jwenn kote feblès yo ye anvan atakè yo fè sa.",
      meto3_name:"🔧 Remedyasyon", meto3_desc:"Nou bay solisyon konkrè pou fèmen pòt yo.",
      meto4_name:"👁️ Siveyans", meto4_desc:"Nou rete avèk ou pou asire pwoteksyon an kontinye.",
      cta_sevis_title:"📞 Rele Nou pou yon Evalyasyon Gratis",
      cta_sevis_desc:"Ou pa sèten ki pake ki bon pou ou? Ekip nou an disponib pou analize bezwen ou epi rekòmande solisyon ki adapte — san frè, san angajman.",
      cta_sevis_btn:"Kontakte Nou →",
      devis_msg:"📋 Pri sou demann — Devis pèsonalize selon bezwen espesifik ou. Kontakte nou pou yon evalyasyon gratis.",
      sur_devis:"Sou devis",
      pake_indiv:"Endividyèl", pake_pme:"PME", pake_ong:"ONG & Enterprise",
      s7_price:"À partir de $44.99 USD oswa 5 880 HTG",
      s8_price:"À partir de $35.00 USD oswa 4 500 HTG",
      s9_price:"À partir de $50.00 USD oswa 6 500 HTG",
      s10_price:"À partir de $99.99 USD oswa 13 000 HTG",
      s1_price:"À partir de $110.00 USD oswa 14 380 HTG",
      s2_price:"À partir de $190.00 USD oswa 24 800 HTG",
      s3_price:"À partir de $165.00 USD oswa 21 500 HTG",
      s4_p_basic:"Analiz debaz:", s4_p_full:"Ankèt konplè:", s4_p_special:"Ka espesyal:",
      s5_p_group:"Gwoup 10–20 moun:", s5_p_corp:"Antrepriz:",
      s6_p_web:"Odit Sit Web:", s6_p_biz:"Odit Biznis:", s6_p_pme:"Odit PME:",
      konsilt_30min:"30 minit", konsilt_1h:"1 èdtan", konsilt_strat:"Plan Estratejik",
      konsilt_p1_30:"$12.99 USD / 1 700 HTG", konsilt_p1_1h:"$25.00 USD / 3 250 HTG",
      konsilt_p2_30:"$15.00 USD / 1 960 HTG", konsilt_p2_1h:"$30.00 USD / 3 900 HTG",
      konsilt_p2_strat:"$90.00 USD+ / 11 760+ HTG"
    },
    fr: {
      nav_brand:"ArmrData", nav_akèy:"Accueil", nav_apropos:"À Propos",
      nav_sevis:"Services", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Affiliation", nav_kontak:"Contact",
      hero_eyebrow:"// Services", hero_title:"Services ArmrData",
      hero_desc:"Nous aidons les particuliers, les entreprises et les organisations à protéger leurs données contre les menaces numériques.",
      antrepriz_label:"// Pour Entreprises", moun_label:"// Pour Particuliers",
      btn_learn:"En Savoir Plus →",
      price_label:"Prix du Service", price_val:"À partir de $39.99 USD ou 5 000 Gourdes",
      ph_antrepriz:"Nom de l'entreprise", ph_adrès:"Adresse de l'entreprise",
      ph_imel:"Email professionnel", ph_kòmantè:"Commentaire — décrivez le service dont vous avez besoin",
      btn_confirm:"Je Suis d'Accord ✓", footer_tag:"Securing your dataworld!",
      s1_title:"Cybersécurité", s1_desc:"Protection des réseaux, systèmes et données sensibles.",
      s1_modal_desc:"Protection des réseaux, systèmes et données sensibles de votre entreprise contre toutes les menaces numériques modernes.",
      s2_title:"Test de Pénétration", s2_desc:"Détectez les failles de sécurité avant les attaquants.",
      s2_modal_desc:"Détectez les failles de sécurité avant les attaquants — une équipe spécialisée teste votre système pour trouver les portes ouvertes.",
      s3_title:"Sécurité Cloud", s3_desc:"Protégez votre infrastructure cloud et vos services numériques.",
      s3_modal_desc:"Protégez votre infrastructure cloud et vos services numériques contre les attaques et les accès non autorisés.",
      s4_title:"Analyse Numérique", s4_desc:"Enquête sur les incidents informatiques et récupération de preuves.",
      s4_modal_desc:"Enquête sur les incidents informatiques et récupération de preuves — identifiez la source de l'attaque et documentez les preuves.",
      s5_title:"Formation", s5_desc:"Formation spécialisée pour équipes et entreprises en sécurité numérique.",
      s5_modal_desc:"Formation spécialisée pour les équipes et entreprises en sécurité numérique — apprenez à protéger vos systèmes efficacement.",
      s6_title:"Audit de Sécurité", s6_desc:"Évaluation complète du système de sécurité de votre entreprise.",
      s6_modal_desc:"Évaluation complète du système de sécurité de votre entreprise pour identifier les risques et recommander des solutions.",
      s7_title:"Protection des Données Personnelles", s7_desc:"Protégez vos informations personnelles contre le vol et la fraude.",
      s7_modal_desc:"Protégez vos informations personnelles contre le vol et la fraude — sécurisez votre identité numérique.",
      s8_title:"Sécurité des Appareils", s8_desc:"Protection des téléphones, tablettes et ordinateurs.",
      s8_modal_desc:"Protection des téléphones, tablettes et ordinateurs contre les menaces et les accès illégaux.",
      s9_title:"Cybersécurité Personnelle", s9_desc:"Protection de vos réseaux, systèmes et données personnelles.",
      s9_modal_desc:"Protection de vos réseaux, systèmes et données personnelles contre toutes les menaces numériques.",
      s10_title:"Test de Pénétration Personnel", s10_desc:"Détectez les failles dans votre système personnel avant les attaquants.",
      s10_modal_desc:"Détectez les failles de sécurité dans votre système personnel avant que les attaquants ne les trouvent.",
      p7_pri:"À partir de $44.99 USD ou 5 880 Gourdes",
      p8_pri:"À partir de $35 USD ou 4 500 Gourdes",
      p9_pri:"À partir de $50 USD ou 6 500 Gourdes",
      p10_pri:"À partir de $99.99 USD ou 13 000 Gourdes",
      p1_pri:"À partir de $110 USD ou 14 380 Gourdes",
      p2_pri:"À partir de $190 USD ou 24 800 Gourdes",
      p3_pri:"À partir de $165 USD ou 21 500 Gourdes",
      p4_pri_title:"Enquête après incident informatique",
      p4_pri_base:"Analyse de base: $175 USD ou 22 800 Gourdes",
      p4_pri_full:"Enquête complète: $310 USD+ ou 40 500+ Gourdes",
      p4_pri_special:"Cas spéciaux: Sur devis",
      p5_pri_title:"Prix du service:",
      p5_pri_group:"Groupe 10-20 personnes: $250 USD ou 32 600 Gourdes",
      p5_pri_biz:"Entreprise: $500 USD ou 65 360 Gourdes",
      p6_pri_web:"Audit Site Web: $110 USD ou 14 380 Gourdes",
      p6_pri_biz:"Audit Entreprise: $300 USD ou 39 200 Gourdes",
      p6_pri_pme:"Audit Enterprise (PME): $650 USD+ ou 84 960 Gourdes",
      konsilt_ind_title:"Prix Consultation:",
      konsilt_ind_30:"30 minutes: $12.99 USD ou 1 700 Gourdes",
      konsilt_ind_60:"1 heure: $25 USD ou 3 250 Gourdes",
      konsilt_pme_30:"30 minutes: $15 USD ou 1 960 Gourdes",
      konsilt_pme_60:"1 heure: $30 USD ou 3 900 Gourdes",
      konsilt_pme_plan:"Plan stratégique: $90 USD+ ou 11 760+ Gourdes",
      konsilt_ong:"Sur demande — Devis personnalisé",
      ong_pri:"Sur demande (Devis personnalisé). Contactez-nous pour une analyse de vos besoins.",
      cta_rele:"📞 Appelez-nous pour une Évaluation Gratuite",
      pake_label:"// Choisissez Votre Forfait",
      pake1_title:"👤 Forfait Individuel (Sécurité Personnelle)",
      pake1_desc:"Idéal pour les personnes qui veulent protéger leurs informations privées, comptes sociaux et téléphone.",
      pake2_title:"🏢 Forfait PME (Petites et Moyennes Entreprises)",
      pake2_desc:"Idéal pour les entreprises qui veulent sécuriser leurs réseaux et informations clients.",
      pake3_title:"🏛️ Forfait ONG & Grandes Entreprises (Enterprise)",
      pake3_desc:"Solutions avancées pour les organisations avec de gros volumes de données et des besoins de conformité.",
      konsilt_title:"Consultation Numérique",
      konsilt_desc:"Parlez à un expert ArmrData gratuitement",
      meto_label:"// Notre Méthodologie",
      meto1_name:"🔍 Analyse", meto1_desc:"Nous évaluons votre niveau de risque actuel.",
      meto2_name:"🎯 Détection", meto2_desc:"Nous trouvons les failles avant les attaquants.",
      meto3_name:"🔧 Remédiation", meto3_desc:"Nous fournissons des solutions concrètes pour fermer les portes.",
      meto4_name:"👁️ Surveillance", meto4_desc:"Nous restons avec vous pour assurer une protection continue.",
      cta_sevis_title:"📞 Appelez-nous pour une Évaluation Gratuite",
      cta_sevis_desc:"Vous n'êtes pas sûr du forfait qui vous convient? Notre équipe est disponible pour analyser vos besoins — sans frais, sans engagement.",
      cta_sevis_btn:"Nous Contacter →",
      devis_msg:"📋 Prix sur demande — Devis personnalisé selon vos besoins spécifiques. Contactez-nous pour une évaluation gratuite.",
      sur_devis:"Sur devis",
      pake_indiv:"Individuel", pake_pme:"PME", pake_ong:"ONG & Enterprise",
      s7_price:"À partir de $44.99 USD ou 5 880 HTG",
      s8_price:"À partir de $35.00 USD ou 4 500 HTG",
      s9_price:"À partir de $50.00 USD ou 6 500 HTG",
      s10_price:"À partir de $99.99 USD ou 13 000 HTG",
      s1_price:"À partir de $110.00 USD ou 14 380 HTG",
      s2_price:"À partir de $190.00 USD ou 24 800 HTG",
      s3_price:"À partir de $165.00 USD ou 21 500 HTG",
      s4_p_basic:"Analyse de base:", s4_p_full:"Enquête complète:", s4_p_special:"Cas spécial:",
      s5_p_group:"Groupe 10–20 personnes:", s5_p_corp:"Entreprise:",
      s6_p_web:"Audit Site Web:", s6_p_biz:"Audit Business:", s6_p_pme:"Audit PME:",
      konsilt_30min:"30 minutes", konsilt_1h:"1 heure", konsilt_strat:"Plan Stratégique",
      konsilt_p1_30:"$12.99 USD / 1 700 HTG", konsilt_p1_1h:"$25.00 USD / 3 250 HTG",
      konsilt_p2_30:"$15.00 USD / 1 960 HTG", konsilt_p2_1h:"$30.00 USD / 3 900 HTG",
      konsilt_p2_strat:"$90.00 USD+ / 11 760+ HTG"
    },
    en: {
      nav_brand:"ArmrData", nav_akèy:"Home", nav_apropos:"About",
      nav_sevis:"Services", nav_ebook:"E-Book", nav_blog:"Blog",
      nav_afilyasyon:"Affiliate", nav_kontak:"Contact",
      hero_eyebrow:"// Services", hero_title:"ArmrData Services",
      hero_desc:"We help individuals, businesses and organizations protect their data against digital threats.",
      antrepriz_label:"// For Businesses", moun_label:"// For Individuals",
      btn_learn:"Learn More →",
      price_label:"Service Price", price_val:"Starting from $39.99 USD or 5,000 Gourdes",
      ph_antrepriz:"Company name", ph_adrès:"Company address",
      ph_imel:"Professional email", ph_kòmantè:"Comment — describe the service you need",
      btn_confirm:"I Agree ✓", footer_tag:"Securing your dataworld!",
      s1_title:"Cybersecurity", s1_desc:"Protection of networks, systems and sensitive data.",
      s1_modal_desc:"Protection of your company's networks, systems and sensitive data against all modern digital threats.",
      s2_title:"Penetration Testing", s2_desc:"Detect security vulnerabilities before attackers do.",
      s2_modal_desc:"Detect security vulnerabilities before attackers — a specialized team tests your system to find open doors.",
      s3_title:"Cloud Security", s3_desc:"Protect your cloud infrastructure and digital services.",
      s3_modal_desc:"Protect your cloud infrastructure and digital services against attacks and unauthorized access.",
      s4_title:"Digital Forensics", s4_desc:"Investigation of computer incidents and evidence recovery.",
      s4_modal_desc:"Investigation of computer incidents and evidence recovery — identify the source of the attack and document the evidence.",
      s5_title:"Training", s5_desc:"Specialized training for teams and businesses in digital security.",
      s5_modal_desc:"Specialized training for teams and businesses in digital security — learn to protect your systems effectively.",
      s6_title:"Security Audit", s6_desc:"Complete evaluation of your company's security system.",
      s6_modal_desc:"Complete evaluation of your company's security system to identify risks and recommend solutions.",
      s7_title:"Personal Data Protection", s7_desc:"Protect your personal information against theft and fraud.",
      s7_modal_desc:"Protect your personal information against theft and fraud — secure your digital identity.",
      s8_title:"Device Security", s8_desc:"Protection of phones, tablets and computers.",
      s8_modal_desc:"Protection of phones, tablets and computers against threats and illegal access.",
      s9_title:"Personal Cybersecurity", s9_desc:"Protection of your personal networks, systems and data.",
      s9_modal_desc:"Protection of your personal networks, systems and data against all digital threats.",
      s10_title:"Personal Penetration Testing", s10_desc:"Detect vulnerabilities in your personal system before attackers.",
      s10_modal_desc:"Detect security vulnerabilities in your personal system before attackers find them.",
      p7_pri:"Starting from $44.99 USD or 5,880 Gourdes",
      p8_pri:"Starting from $35 USD or 4,500 Gourdes",
      p9_pri:"Starting from $50 USD or 6,500 Gourdes",
      p10_pri:"Starting from $99.99 USD or 13,000 Gourdes",
      p1_pri:"Starting from $110 USD or 14,380 Gourdes",
      p2_pri:"Starting from $190 USD or 24,800 Gourdes",
      p3_pri:"Starting from $165 USD or 21,500 Gourdes",
      p4_pri_title:"Post-incident investigation",
      p4_pri_base:"Basic analysis: $175 USD or 22,800 Gourdes",
      p4_pri_full:"Full investigation: $310 USD+ or 40,500+ Gourdes",
      p4_pri_special:"Special cases: On quote",
      p5_pri_title:"Service price:",
      p5_pri_group:"Group 10-20 people: $250 USD or 32,600 Gourdes",
      p5_pri_biz:"Enterprise: $500 USD or 65,360 Gourdes",
      p6_pri_web:"Website Audit: $110 USD or 14,380 Gourdes",
      p6_pri_biz:"Business Audit: $300 USD or 39,200 Gourdes",
      p6_pri_pme:"Enterprise Audit (SMB): $650 USD+ or 84,960 Gourdes",
      konsilt_ind_title:"Consultation Price:",
      konsilt_ind_30:"30 minutes: $12.99 USD or 1,700 Gourdes",
      konsilt_ind_60:"1 hour: $25 USD or 3,250 Gourdes",
      konsilt_pme_30:"30 minutes: $15 USD or 1,960 Gourdes",
      konsilt_pme_60:"1 hour: $30 USD or 3,900 Gourdes",
      konsilt_pme_plan:"Strategic plan: $90 USD+ or 11,760+ Gourdes",
      konsilt_ong:"On request — Personalized quote",
      ong_pri:"On request (Personalized quote). Contact us for a specific needs analysis.",
      cta_rele:"📞 Call Us for a Free Evaluation",
      pake_label:"// Choose Your Package",
      pake1_title:"👤 Individual Package (Personal Security)",
      pake1_desc:"Ideal for people who want to protect their private information, social accounts and phone.",
      pake2_title:"🏢 SME Package (Small and Medium Businesses)",
      pake2_desc:"Ideal for businesses that want to secure their networks and customer information.",
      pake3_title:"🏛️ NGO & Large Enterprise Package",
      pake3_desc:"Advanced solutions for organizations with large data volumes and compliance needs.",
      konsilt_title:"Digital Consultation",
      konsilt_desc:"Talk to an ArmrData expert for free",
      meto_label:"// Our Methodology",
      meto1_name:"🔍 Analysis", meto1_desc:"We evaluate your current risk level.",
      meto2_name:"🎯 Detection", meto2_desc:"We find vulnerabilities before attackers do.",
      meto3_name:"🔧 Remediation", meto3_desc:"We provide concrete solutions to close the doors.",
      meto4_name:"👁️ Monitoring", meto4_desc:"We stay with you to ensure continuous protection.",
      cta_sevis_title:"📞 Call Us for a Free Evaluation",
      cta_sevis_desc:"Not sure which package is right for you? Our team is available to analyze your needs and recommend tailored solutions — free, no commitment.",
      cta_sevis_btn:"Contact Us →",
      devis_msg:"📋 Price on request — Personalized quote based on your specific needs. Contact us for a free evaluation.",
      sur_devis:"On request",
      pake_indiv:"Individual", pake_pme:"SME", pake_ong:"NGO & Enterprise",
      s7_price:"Starting from $44.99 USD or 5,880 HTG",
      s8_price:"Starting from $35.00 USD or 4,500 HTG",
      s9_price:"Starting from $50.00 USD or 6,500 HTG",
      s10_price:"Starting from $99.99 USD or 13,000 HTG",
      s1_price:"Starting from $110.00 USD or 14,380 HTG",
      s2_price:"Starting from $190.00 USD or 24,800 HTG",
      s3_price:"Starting from $165.00 USD or 21,500 HTG",
      s4_p_basic:"Basic analysis:", s4_p_full:"Full investigation:", s4_p_special:"Special case:",
      s5_p_group:"Group 10–20 people:", s5_p_corp:"Enterprise:",
      s6_p_web:"Website Audit:", s6_p_biz:"Business Audit:", s6_p_pme:"SME Audit:",
      konsilt_30min:"30 minutes", konsilt_1h:"1 hour", konsilt_strat:"Strategic Plan",
      konsilt_p1_30:"$12.99 USD / 1,700 HTG", konsilt_p1_1h:"$25.00 USD / 3,250 HTG",
      konsilt_p2_30:"$15.00 USD / 1,960 HTG", konsilt_p2_1h:"$30.00 USD / 3,900 HTG",
      konsilt_p2_strat:"$90.00 USD+ / 11,760+ HTG"
    }
  }
};

// ── TRADIKSYON MODAL BLOG ──
const blogModals = {
  ht: {
    konsèy_label:"Konsèy ArmrData",
    m1_eyebrow:"Rezo Sosyal",
    m1_meta:"📅 Jen 2026 • ✍️ Ekip ArmrData • ⏱️ 4 min lekti",
    m1_title:"5 Erè Sekirite Moun Fè Sou Facebook",
    m1_intro:"Facebook se youn nan rezo sosyal ki pi itilize sou planèt la. Chak jou, milyon moun pataje foto, enfòmasyon pèsonèl ak mesaj sou platfòm sa a. Malerezman, anpil itilizatè pa rann yo kont ke kèk abitid senp ka mete vi prive yo ak sekirite yo an danje.",
    m1_intro2:"Men 5 erè ki pi komen yo ak fason pou evite yo.",
    m1_h1:"1. Itilize menm modpas la pou tout kont yo",
    m1_p1:"Anpil moun itilize menm modpas la pou Facebook, Gmail, Instagram ak lòt sèvis yo. Sa ka sanble pratik, men se youn nan pi gwo erè sekirite ou ka fè.",
    m1_p2:"Si yon sèl sit entènèt sibi yon vyolasyon done epi modpas ou ekspoze, yon atakan ka eseye menm modpas la sou lòt kont ou yo.",
    m1_k1:"Sèvi ak yon modpas diferan pou chak sèvis epi itilize yon manadjè modpas pou ede w jere yo.",
    m1_h2:"2. Pa aktive verifikasyon an de etap (2FA)",
    m1_p3:"Yon modpas fò enpòtan, men li pa toujou sifi. Si yon moun rive jwenn modpas ou, li ka konekte sou kont ou fasil.",
    m1_p4:"Se la verifikasyon an de etap la antre an jwèt. Lè 2FA aktive, sistèm nan mande yon dezyèm kòd sekirite anplis modpas la.",
    m1_k2:"Itilize Google Authenticator oswa Microsoft Authenticator pito pase SMS lè sa posib.",
    m1_h3:"3. Aksepte demann zanmi nenpòt moun",
    m1_p5:"Fo pwofil yo se youn nan zouti ki pi itilize pou kolekte enfòmasyon sou moun.",
    m1_p6:"Yon moun ka kreye yon pwofil ki sanble nòmal, ajoute kèk foto epi voye dè santèn demann zanmi. Lè yo aksepte l, li jwenn aksè ak anpil enfòmasyon prive.",
    m1_k3:"Verifye pwofil yon moun anvan ou aksepte demann li.",
    m1_h4:"4. Klike sou nenpòt lyen yo voye ba ou",
    m1_p7:"Atak phishing yo souvan kòmanse ak yon mesaj ki sanble lejitim.",
    m1_p8:"Ou ka resevwa yon mesaj ki di: \"Gade foto sa a!\" \"Kont ou pral fèmen!\" oswa \"Ou genyen yon pri!\"",
    m1_p9:"Lè ou klike, yo ka mennen ou sou yon fo sit ki fèt pou vòlè modpas ou.",
    m1_k4:"Toujou verifye adrès sit la anvan ou antre nenpòt enfòmasyon pèsonèl.",
    m1_h5:"5. Pataje twòp enfòmasyon pèsonèl",
    m1_p10:"Dat nesans, nimewo telefòn, adrès oswa enfòmasyon sou fanmi kapab ede yon atakan prepare yon atak ki pi vize.",
    m1_p11:"Mwens enfòmasyon piblik ou bay, se plis sekirite ou genyen.",
    m1_k5:"Revize paramèt vi prive Facebook ou regilyèman.",
    m1_hkonk:"Konklizyon",
    m1_konk1:"Sekirite dijital pa depann sèlman de teknoloji; li depann tou de abitid nou chak jou.",
    m1_konk2:"Lè ou evite 5 erè sa yo, ou diminye anpil chans pou yon moun konpwomèt kont Facebook ou.",
    m2_eyebrow:"Modpas",
    m2_meta:"📅 Jen 2026 • ✍️ Ekip ArmrData • ⏱️ 3 min lekti",
    m2_title:"Kijan Pou Kreye Yon Modpas Fò An 2026",
    m2_intro:"Modpas ou se premye pòt ki pwoteje lavi dijital ou. Kit se Facebook, Gmail, WhatsApp oswa kont bank ou, tout bagay kòmanse ak yon modpas. Malerezman, anpil moun toujou itilize modpas ki fasil pou devine tankou non yo, dat nesans yo oswa sekans chif senp.",
    m2_h1:"Poukisa yon Modpas Fò Enpòtan?",
    m2_p1:"Yon modpas fò ede pwoteje enfòmasyon pèsonèl ou, foto ou, mesaj ou ak done finansye ou. Li sèvi kòm premye baryè ant ou menm ak moun ki ta vle jwenn aksè san otorizasyon nan kont ou yo.",
    m2_h2:"Danje Yon Modpas Fèb",
    m2_p2:"Lè yon modpas twò senp, li kapab fasil pou devine oswa kraze atravè zouti otomatik. Sa kapab mennen nan:",
    m2_li1:"Vòl idantite", m2_li2:"Pèt aksè ak kont yo",
    m2_li3:"Fwod finansye", m2_li4:"Vòl done pèsonèl",
    m2_li5:"Domaj pou repitasyon yon biznis",
    m2_hkonk:"Konklizyon",
    m2_konk:"Kreye yon modpas fò pa yon kestyon chans. Li mande bon pratik ak bon zouti. Nan atik sa a nou sèlman prezante enpòtans sijè a. Pou aprann teknik pwofesyonèl yo itilize pou kreye modpas ki solid, kijan pou konstwi yon fraz-pas efikas, ansanm ak zouti rekòmande pou jere modpas yo an sekirite, nou envite w li:",
    m2_ebook:"📖 Blendaj Dijital — 7 Etap Pou Pwoteje Tèt Ou Ak Biznis Ou Kont Pirat",
    m2_ebook_btn:"Dekouvri Ebook la",
    m3_eyebrow:"Phishing",
    m3_meta:"📅 Jen 2026 • ✍️ Ekip ArmrData • ⏱️ 4 min lekti",
    m3_title:"Phishing: Pi Gwo Pyèj Dijital Jodi a",
    m3_intro:"Nan mond dijital jodi a, anpil moun panse pi gwo menas yo se viris oswa gwo pirat enfòmatik. Men an reyalite, youn nan teknik ki fè plis viktim chak ane se phishing. Phishing se yon teknik kote yon atakan eseye twonpe yon moun pou fè l bay enfòmasyon sansib tankou modpas, enfòmasyon bankè oswa kòd sekirite.",
    m3_h1:"Poukisa Phishing Danjere?",
    m3_p1:"Kontrèman ak anpil lòt atak, phishing pa chèche kraze sistèm yo an premye. Li chèche twonpe moun. Yon mesaj ka sanble soti nan:",
    m3_li1:"Facebook", m3_li2:"Google", m3_li3:"Bank ou",
    m3_li4:"Yon zanmi", m3_li5:"Yon antrepriz ou fè konfyans",
    m3_p2:"Se poutèt sa anpil moun tonbe nan pyèj la. Mesaj la souvan sanble reyèl.",
    m3_h2:"Ki Risk Ki Genyen?",
    m3_p3:"Yon atak phishing reyisi kapab lakoz:",
    m3_li6:"Vòl modpas", m3_li7:"Pèt aksè ak kont yo",
    m3_li8:"Fwod finansye", m3_li9:"Vòl done pèsonèl",
    m3_li10:"Konpwomisyon yon antrepriz antye",
    m3_h3:"Yon Teknik Senp Pou Pwoteje Tèt Ou",
    m3_p4:"Anvan ou klike sou nenpòt lyen ki vini pa imèl, WhatsApp oswa Messenger:",
    m3_alèt:"Kanpe. Li mesaj la ankò. Verifye kiyès ki voye li.",
    m3_p5:"Si mesaj la ap mete presyon sou ou, mande w prese oswa fè w pè — pran plis prekosyon toujou.",
    m3_hkonk:"Konklizyon",
    m3_konk:"Teknik sa a kapab ede anpil, men phishing modèn yo vin pi sofistike chak ane. Pou aprann:",
    m3_li11:"Kijan pou rekonèt yon move lyen",
    m3_li12:"Teknik Hover la",
    m3_li13:"Kijan pou verifye imèl yo",
    m3_li14:"Siy ki montre yon sit entènèt se yon fo sit",
    m3_li15:"Metòd pwofesyonèl pou pwoteje biznis ou",
    m3_ebook:"📖 Blendaj Dijital — 7 Etap Pou Pwoteje Tèt Ou Ak Biznis Ou Kont Pirat",
    m3_ebook_btn:"Dekouvri Ebook la"
  },
  fr: {
    konsèy_label:"Conseil ArmrData",
    m1_eyebrow:"Réseau Social",
    m1_meta:"📅 Juin 2026 • ✍️ Équipe ArmrData • ⏱️ 4 min de lecture",
    m1_title:"5 Erreurs de Sécurité que les Gens Font sur Facebook",
    m1_intro:"Facebook est l'un des réseaux sociaux les plus utilisés sur la planète. Chaque jour, des millions de personnes partagent des photos, des informations personnelles et des messages sur cette plateforme. Malheureusement, beaucoup d'utilisateurs ne réalisent pas que certaines habitudes simples peuvent mettre leur vie privée et leur sécurité en danger.",
    m1_intro2:"Voici les 5 erreurs les plus courantes et comment les éviter.",
    m1_h1:"1. Utiliser le même mot de passe pour tous les comptes",
    m1_p1:"Beaucoup de gens utilisent le même mot de passe pour Facebook, Gmail, Instagram et d'autres services. Cela peut sembler pratique, mais c'est l'une des plus grandes erreurs de sécurité que vous puissiez faire.",
    m1_p2:"Si un seul site web subit une violation de données et que votre mot de passe est exposé, un attaquant peut essayer le même mot de passe sur vos autres comptes.",
    m1_k1:"Utilisez un mot de passe différent pour chaque service et utilisez un gestionnaire de mots de passe pour vous aider à les gérer.",
    m1_h2:"2. Ne pas activer la vérification en deux étapes (2FA)",
    m1_p3:"Un mot de passe fort est important, mais il n'est pas toujours suffisant. Si quelqu'un parvient à obtenir votre mot de passe, il peut facilement se connecter à votre compte.",
    m1_p4:"C'est là que la vérification en deux étapes entre en jeu. Lorsque le 2FA est activé, le système demande un deuxième code de sécurité en plus du mot de passe.",
    m1_k2:"Utilisez Google Authenticator ou Microsoft Authenticator plutôt que les SMS lorsque c'est possible.",
    m1_h3:"3. Accepter les demandes d'amis de n'importe qui",
    m1_p5:"Les faux profils sont l'un des outils les plus utilisés pour collecter des informations sur les personnes.",
    m1_p6:"Quelqu'un peut créer un profil qui semble normal, ajouter quelques photos et envoyer des centaines de demandes d'amis. Une fois accepté, il accède à beaucoup d'informations privées.",
    m1_k3:"Vérifiez le profil d'une personne avant d'accepter sa demande.",
    m1_h4:"4. Cliquer sur n'importe quel lien qu'on vous envoie",
    m1_p7:"Les attaques de phishing commencent souvent par un message qui semble légitime.",
    m1_p8:"Vous pouvez recevoir un message disant: \"Regardez cette photo!\" \"Votre compte va être fermé!\" ou \"Vous avez gagné un prix!\"",
    m1_p9:"En cliquant, vous pouvez être redirigé vers un faux site conçu pour voler votre mot de passe.",
    m1_k4:"Vérifiez toujours l'adresse du site avant de saisir des informations personnelles.",
    m1_h5:"5. Partager trop d'informations personnelles",
    m1_p10:"La date de naissance, le numéro de téléphone, l'adresse ou les informations familiales peuvent aider un attaquant à préparer une attaque plus ciblée.",
    m1_p11:"Moins vous donnez d'informations publiques, plus vous êtes en sécurité.",
    m1_k5:"Révisez régulièrement vos paramètres de confidentialité Facebook.",
    m1_hkonk:"Conclusion",
    m1_konk1:"La sécurité numérique ne dépend pas seulement de la technologie; elle dépend aussi de nos habitudes quotidiennes.",
    m1_konk2:"En évitant ces 5 erreurs, vous réduisez considérablement les chances qu'une personne compromette votre compte Facebook.",
    m2_eyebrow:"Mot de passe",
    m2_meta:"📅 Juin 2026 • ✍️ Équipe ArmrData • ⏱️ 3 min de lecture",
    m2_title:"Comment Créer un Mot de Passe Fort en 2026",
    m2_intro:"Votre mot de passe est la première porte qui protège votre vie numérique. Que ce soit Facebook, Gmail, WhatsApp ou votre compte bancaire, tout commence par un mot de passe. Malheureusement, beaucoup de gens utilisent encore des mots de passe faciles à deviner.",
    m2_h1:"Pourquoi un Mot de Passe Fort est-il Important?",
    m2_p1:"Un mot de passe fort aide à protéger vos informations personnelles, vos photos, vos messages et vos données financières. Il sert de première barrière entre vous et les personnes qui voudraient accéder à vos comptes sans autorisation.",
    m2_h2:"Les Dangers d'un Mot de Passe Faible",
    m2_p2:"Lorsqu'un mot de passe est trop simple, il peut facilement être deviné ou craqué par des outils automatiques. Cela peut conduire à:",
    m2_li1:"Vol d'identité", m2_li2:"Perte d'accès aux comptes",
    m2_li3:"Fraude financière", m2_li4:"Vol de données personnelles",
    m2_li5:"Atteinte à la réputation d'une entreprise",
    m2_hkonk:"Conclusion",
    m2_konk:"Créer un mot de passe fort n'est pas une question de chance. Cela demande de bonnes pratiques et de bons outils. Dans cet article, nous présentons seulement l'importance du sujet. Pour apprendre les techniques professionnelles, nous vous invitons à lire:",
    m2_ebook:"📖 Blindage Digital — 7 Étapes Pour Vous Protéger Contre les Pirates",
    m2_ebook_btn:"Découvrir l'Ebook",
    m3_eyebrow:"Phishing",
    m3_meta:"📅 Juin 2026 • ✍️ Équipe ArmrData • ⏱️ 4 min de lecture",
    m3_title:"Phishing: Le Plus Grand Piège Numérique Aujourd'hui",
    m3_intro:"Dans le monde numérique d'aujourd'hui, beaucoup de gens pensent que les plus grandes menaces sont les virus ou les grands pirates informatiques. Mais en réalité, l'une des techniques qui fait le plus de victimes chaque année est le phishing.",
    m3_h1:"Pourquoi le Phishing est-il Dangereux?",
    m3_p1:"Contrairement à beaucoup d'autres attaques, le phishing ne cherche pas d'abord à pirater les systèmes. Il cherche à tromper les gens. Un message peut sembler provenir de:",
    m3_li1:"Facebook", m3_li2:"Google", m3_li3:"Votre banque",
    m3_li4:"Un ami", m3_li5:"Une entreprise en qui vous avez confiance",
    m3_p2:"C'est pourquoi beaucoup de gens tombent dans le piège. Le message semble souvent réel.",
    m3_h2:"Quels sont les Risques?",
    m3_p3:"Une attaque de phishing réussie peut causer:",
    m3_li6:"Vol de mot de passe", m3_li7:"Perte d'accès aux comptes",
    m3_li8:"Fraude financière", m3_li9:"Vol de données personnelles",
    m3_li10:"Compromission d'une entreprise entière",
    m3_h3:"Une Technique Simple Pour Se Protéger",
    m3_p4:"Avant de cliquer sur n'importe quel lien reçu par email, WhatsApp ou Messenger:",
    m3_alèt:"Arrêtez. Relisez le message. Vérifiez qui l'a envoyé.",
    m3_p5:"Si le message vous met sous pression, vous demande de vous dépêcher ou vous fait peur — soyez encore plus prudent.",
    m3_hkonk:"Conclusion",
    m3_konk:"Cette technique peut beaucoup aider, mais les phishings modernes deviennent de plus en plus sophistiqués. Pour apprendre:",
    m3_li11:"Comment reconnaître un mauvais lien",
    m3_li12:"La technique du survol (Hover)",
    m3_li13:"Comment vérifier les emails",
    m3_li14:"Les signes qu'un site web est faux",
    m3_li15:"Les méthodes professionnelles pour protéger votre entreprise",
    m3_ebook:"📖 Blindage Digital — 7 Étapes Pour Vous Protéger Contre les Pirates",
    m3_ebook_btn:"Découvrir l'Ebook"
  },
  en: {
    konsèy_label:"ArmrData Tip",
    m1_eyebrow:"Social Media",
    m1_meta:"📅 June 2026 • ✍️ ArmrData Team • ⏱️ 4 min read",
    m1_title:"5 Security Mistakes People Make on Facebook",
    m1_intro:"Facebook is one of the most used social networks on the planet. Every day, millions of people share photos, personal information and messages on this platform. Unfortunately, many users don't realize that some simple habits can put their privacy and security at risk.",
    m1_intro2:"Here are the 5 most common mistakes and how to avoid them.",
    m1_h1:"1. Using the same password for all accounts",
    m1_p1:"Many people use the same password for Facebook, Gmail, Instagram and other services. This may seem convenient, but it's one of the biggest security mistakes you can make.",
    m1_p2:"If a single website suffers a data breach and your password is exposed, an attacker can try the same password on your other accounts.",
    m1_k1:"Use a different password for each service and use a password manager to help you manage them.",
    m1_h2:"2. Not enabling two-step verification (2FA)",
    m1_p3:"A strong password is important, but it's not always enough. If someone manages to get your password, they can easily log into your account.",
    m1_p4:"That's where two-step verification comes in. When 2FA is enabled, the system asks for a second security code in addition to the password.",
    m1_k2:"Use Google Authenticator or Microsoft Authenticator rather than SMS when possible.",
    m1_h3:"3. Accepting friend requests from anyone",
    m1_p5:"Fake profiles are one of the most used tools to collect information about people.",
    m1_p6:"Someone can create a profile that looks normal, add some photos and send hundreds of friend requests. Once accepted, they gain access to a lot of private information.",
    m1_k3:"Check a person's profile before accepting their request.",
    m1_h4:"4. Clicking on any link sent to you",
    m1_p7:"Phishing attacks often start with a message that seems legitimate.",
    m1_p8:"You may receive a message saying: \"Look at this photo!\" \"Your account will be closed!\" or \"You won a prize!\"",
    m1_p9:"When you click, you may be taken to a fake site designed to steal your password.",
    m1_k4:"Always verify the site address before entering any personal information.",
    m1_h5:"5. Sharing too much personal information",
    m1_p10:"Date of birth, phone number, address or family information can help an attacker prepare a more targeted attack.",
    m1_p11:"The less public information you share, the more secure you are.",
    m1_k5:"Regularly review your Facebook privacy settings.",
    m1_hkonk:"Conclusion",
    m1_konk1:"Digital security doesn't depend only on technology; it also depends on our daily habits.",
    m1_konk2:"By avoiding these 5 mistakes, you greatly reduce the chances of someone compromising your Facebook account.",
    m2_eyebrow:"Password",
    m2_meta:"📅 June 2026 • ✍️ ArmrData Team • ⏱️ 3 min read",
    m2_title:"How to Create a Strong Password in 2026",
    m2_intro:"Your password is the first door protecting your digital life. Whether it's Facebook, Gmail, WhatsApp or your bank account, everything starts with a password. Unfortunately, many people still use passwords that are easy to guess like their name, date of birth or simple number sequences.",
    m2_h1:"Why is a Strong Password Important?",
    m2_p1:"A strong password helps protect your personal information, photos, messages and financial data. It serves as the first barrier between you and people who want to access your accounts without authorization.",
    m2_h2:"The Dangers of a Weak Password",
    m2_p2:"When a password is too simple, it can easily be guessed or cracked by automated tools. This can lead to:",
    m2_li1:"Identity theft", m2_li2:"Loss of account access",
    m2_li3:"Financial fraud", m2_li4:"Personal data theft",
    m2_li5:"Damage to a business reputation",
    m2_hkonk:"Conclusion",
    m2_konk:"Creating a strong password is not a matter of chance. It requires good practices and good tools. In this article we only present the importance of the subject. To learn professional techniques, we invite you to read:",
    m2_ebook:"📖 Digital Shield — 7 Steps to Protect Yourself and Your Business Against Hackers",
    m2_ebook_btn:"Discover the Ebook",
    m3_eyebrow:"Phishing",
    m3_meta:"📅 June 2026 • ✍️ ArmrData Team • ⏱️ 4 min read",
    m3_title:"Phishing: The Biggest Digital Trap Today",
    m3_intro:"In today's digital world, many people think the biggest threats are viruses or major hackers. But in reality, one of the techniques that claims the most victims every year is phishing.",
    m3_h1:"Why is Phishing Dangerous?",
    m3_p1:"Unlike many other attacks, phishing doesn't first seek to hack systems. It seeks to trick people. A message can appear to come from:",
    m3_li1:"Facebook", m3_li2:"Google", m3_li3:"Your bank",
    m3_li4:"A friend", m3_li5:"A company you trust",
    m3_p2:"That's why many people fall into the trap. The message often seems real.",
    m3_h2:"What are the Risks?",
    m3_p3:"A successful phishing attack can cause:",
    m3_li6:"Password theft", m3_li7:"Loss of account access",
    m3_li8:"Financial fraud", m3_li9:"Personal data theft",
    m3_li10:"Compromise of an entire business",
    m3_h3:"A Simple Technique to Protect Yourself",
    m3_p4:"Before clicking on any link received by email, WhatsApp or Messenger:",
    m3_alèt:"Stop. Read the message again. Verify who sent it.",
    m3_p5:"If the message pressures you, asks you to hurry or makes you afraid — take extra precautions.",
    m3_hkonk:"Conclusion",
    m3_konk:"This technique can help a lot, but modern phishing attacks are becoming more sophisticated every year. To learn:",
    m3_li11:"How to recognize a bad link",
    m3_li12:"The Hover technique",
    m3_li13:"How to verify emails",
    m3_li14:"Signs that a website is fake",
    m3_li15:"Professional methods to protect your business",
    m3_ebook:"📖 Digital Shield — 7 Steps to Protect Yourself and Your Business Against Hackers",
    m3_ebook_btn:"Discover the Ebook"
  }
};

// ── FONKSYON PRENSIPAL ──
function getLang() {
  return localStorage.getItem('armrdata_lang') || 'ht';
}

function setLang(lang) {
  localStorage.setItem('armrdata_lang', lang);
}

function applyTranslations(page) {
  var lang = getLang();
  var t = translations[page] && translations[page][lang];
  if (!t) return;
  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    var key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) {
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
        el.placeholder = t[key];
      } else {
        el.textContent = t[key];
      }
    }
  });
}

function applyBlogModals() {
  var lang = getLang();
  var t = blogModals[lang];
  if (!t) return;
  document.querySelectorAll('[data-modal-i18n]').forEach(function(el) {
    var key = el.getAttribute('data-modal-i18n');
    if (t[key] !== undefined) {
      el.textContent = t[key];
    }
  });
}

function toggleLangMenu() {
  var menu = document.getElementById('langMenu');
  if (menu) menu.classList.toggle('open');
}

function closeLangMenu() {
  var menu = document.getElementById('langMenu');
  if (menu) menu.classList.remove('open');
}

function initLangSwitcher(page) {
  var current = getLang();
  document.querySelectorAll('.lang-option').forEach(function(btn) {
    if (btn.getAttribute('data-lang') === current) {
      btn.classList.add('active');
    }
    btn.addEventListener('click', function() {
      var lang = this.getAttribute('data-lang');
      setLang(lang);
      document.querySelectorAll('.lang-option').forEach(function(b) {
        b.classList.remove('active');
      });
      this.classList.add('active');
      applyTranslations(page);
      if (page === 'blog') applyBlogModals();
      closeLangMenu();
    });
  });
  applyTranslations(page);
  if (page === 'blog') applyBlogModals();
}

document.addEventListener('click', function(e) {
  if (!e.target.closest('.lang-switcher')) closeLangMenu();
});


